- app/Resources/views/grid/content.html.twig
- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/199/ which resulted in this pull request.
> Updated elife/patterns to c747276: Updated pattern-library to c86d341: Hide the view selector on smaller screens when there's only one link

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/202/ which resulted in this pull request.
> Updated elife/patterns to 708c15a: Updated pattern-library to 3034cbd: Reduce polyfills

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/203/ which resulted in this pull request.
> Updated elife/patterns to 2991e25: Updated pattern-library to 29dd53c: Fix logo sizes

- composer.lock
- src/Controller/AboutController.php
- src/Controller/ArchiveController.php
- src/ViewModel/Converter/ArticleContentHeaderConverter.php
- src/ViewModel/Converter/BlogArticleContentHeaderConverter.php
- src/ViewModel/Converter/CollectionContentHeaderConverter.php
- src/ViewModel/Converter/EventContentHeaderConverter.php
- src/ViewModel/Converter/InterviewContentHeaderConverter.php
- src/ViewModel/Converter/LabsPostContentHeaderConverter.php
- src/ViewModel/Converter/PodcastEpisodeContentHeaderConverter.php
- src/ViewModel/Converter/PressPackageContentHeaderConverter.php
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/205/ which resulted in this pull request.
> Updated elife/patterns to ce87002: Updated pattern-library to 24060d9: ELPP-2789 Link First Author et al to details section (narrow)

- app/Resources/views/archive-month.html.twig
- app/Resources/views/article-text.html.twig
- app/Resources/views/collection.html.twig
- app/Resources/views/community.html.twig
- app/Resources/views/contact.html.twig
- app/Resources/views/home.html.twig
- app/Resources/views/magazine.html.twig
- app/Resources/views/podcast-episode.html.twig
- app/Resources/views/press-pack.html.twig
- app/Resources/views/press-packs.html.twig
- app/Resources/views/search.html.twig
- app/Resources/views/subject.html.twig
- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/209/ which resulted in this pull request.
> Updated elife/patterns to 6657513: Updated pattern-library to a9bfa77: Add grid-secondary-column__item

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/210/ which resulted in this pull request.
> Updated elife/patterns to a45f306: Updated pattern-library to cdf19bc: Fix display of superscript and subscript in figure caption body

- app/config/config_baseline.yml
- bin/console
- web/app_baseline.php
To be used by thedailybugle.org as the simplest configuration to deploy on AWS
> New environment: baseline

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/212/ which resulted in this pull request.
> Updated elife/patterns to 947a8d9: Updated pattern-library to 04b946b: Make grid listings full width

- composer.lock
- src/Controller/AboutController.php
- src/Controller/ArchiveController.php
- src/ViewModel/Converter/FormViewConverter.php
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/213/ which resulted in this pull request.
> Updated elife/patterns to 54a76f7: Update form fields

- app/config/config.yml
- app/config/config_baseline.yml
- app/config/config_prod.yml
- app/config/parameters.yml.dist
- app/config/services.yml
- app/config/services_prod.yml
Bit more difficult than I'd hoped to create alternative cache adapters.
> ELPP-2905 Separate HTTP cache adapter

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/214/ which resulted in this pull request.
> Updated elife/patterns to d73a52c: Updated pattern-library to 070e232: Restrict universal selector to top level

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/216/ which resulted in this pull request.
> Updated elife/patterns to a2a72f4: Updated pattern-library to cf74765: Don't include actions if there are none

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/218/ which resulted in this pull request.
> Updated elife/patterns to bf70385: Updated pattern-library to 5a31b2a: Make sure all target="_blank" have rel="noopener noreferrer"

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/219/ which resulted in this pull request.
> Updated elife/patterns to 021bfc9: Updated pattern-library to bf2d437: Avoid extra spaces inside the inline list

- app/config/config.yml
Doesn't seem to work - https://github.com/nelmio/NelmioSecurityBundle/issues/28#issuecomment-313605136
(Not sure why it works in the tests.)
> Remove signed cookies

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/222/ which resulted in this pull request.
> Updated elife/patterns to dfd7f12: Updated pattern-library to a85023b: PI-192 Add sequence class

- app/config/config_baseline.yml
services_prod.yml has been removed and should not be included here
> Update baseline configuration

- npm-shrinkwrap.json
Brings `npm-shrinkwrap.json` in line with current `package.json`.
> Update `npm-shrinkwrap.json` with full dependencies

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/225/ which resulted in this pull request.
> Updated elife/patterns to 5481ab1: Updated pattern-library to 5a0ac92: ELPP-1965: jump menu highlighting based on page scroll

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/226/ which resulted in this pull request.
> Updated elife/patterns to 8905be4: Updated pattern-library to bc49afb: Implement requested design changes to view selector

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/228/ which resulted in this pull request.
> Updated elife/patterns to 4fe5391: Updated pattern-library to d73ec01: Update download menu styles

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/229/ which resulted in this pull request.
> Updated elife/patterns to 406ff67: Updated pattern-library to 437d77b: ELPP-3007 Turn multiple author details values into a bulleted list

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/231/ which resulted in this pull request.
> Updated elife/patterns to 62cc47f: Updated pattern-library to ae06874: ELPP-2624 About profiles grid

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/232/ which resulted in this pull request.
> Updated elife/patterns to 781f265: Updated pattern-library to 9ea06e7: ELPP-2826 Update figure spacing

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/233/ which resulted in this pull request.
> Updated elife/patterns to f729cbb: Updated pattern-library to 8bebadf: Fix <dt> margin-top

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/234/ which resulted in this pull request.
> Updated elife/patterns to 1f89303: Updated pattern-library to be9d61b: ELPP-3013 Inline image height

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/236/ which resulted in this pull request.
> Updated elife/patterns to 91eb40c: Updated pattern-library to 8dbc640: ELPP-3010 Fix Fragment handling

- composer.lock
- src/ViewModel/Converter/BlogArticleContentHeaderConverter.php
- src/ViewModel/Converter/EventContentHeaderConverter.php
- src/ViewModel/Converter/InterviewContentHeaderConverter.php
- src/ViewModel/Converter/LabsPostContentHeaderConverter.php
- src/ViewModel/Converter/PodcastEpisodeContentHeaderConverter.php
- src/ViewModel/Converter/PressPackageContentHeaderConverter.php
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/237/ which resulted in this pull request.
> Updated elife/patterns to 1dfced5: Updated pattern-library to 8a09ad3: Tweak content header spacing

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/238/ which resulted in this pull request.
> Updated elife/patterns to 19f7bc6: Updated pattern-library to 598668f: Remove bold from content header impact statements

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/240/ which resulted in this pull request.
> Updated elife/patterns to 9ea5222: Updated pattern-library to 543515e: ELPP-2843 Only show the spinner when loading more

- composer.lock
- gulpfile.js
- src/Controller/WhoWeWorkWithController.php
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/241/ which resulted in this pull request.
> Updated elife/patterns to bb7359f: Updated pattern-library to 2dc85cb: ELPP-2837 Update image link size

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/243/ which resulted in this pull request.
> Updated elife/patterns to ad4e2ad: Updated pattern-library to 621d177: ELPP-2831 Increase space above meta info

- composer.lock
- src/ViewModel/Converter/ArticleTeaserConverter.php
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/244/ which resulted in this pull request.
> Updated elife/patterns to 391f9d5: Updated pattern-library to bbf4377: ELPP-2820 ELPP-2412 Teaser format

- app/Resources/views/archive-month.html.twig
- composer.lock
- src/Controller/ArchiveController.php
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/246/ which resulted in this pull request.
> Updated elife/patterns to ce7a5ff: Updated pattern-library to 896014a: ELPP-3019 Separate image credit overlay from the text

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/248/ which resulted in this pull request.
> Updated elife/patterns to 8484e0c: Updated pattern-library to 91a0d0a: Update content header simple

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/249/ which resulted in this pull request.
> Updated elife/patterns to fe180e0: Updated pattern-library to ea4b30c: Remove superfluous IDs

- app/Resources/views/exception.html.twig
- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/251/ which resulted in this pull request.
> Updated elife/patterns to 3931793: Updated pattern-library to 1da3f31: Search tweaks

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/253/ which resulted in this pull request.
> Updated elife/patterns to dbb3d75: Updated pattern-library to addcb83: Harden section listing link

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/256/ which resulted in this pull request.
> Updated elife/patterns to 0312951: Updated pattern-library to acb0a63: Remove main menu hover colours

- composer.lock
- features/bootstrap/SearchContext.php
- features/search-refinements.feature
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/258/ which resulted in this pull request.
> Updated elife/patterns to 6795c89: Updated pattern-library to cd9bd68: ELPP-2071 Submit form on a filter changing

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/260/ which resulted in this pull request.
> Updated elife/patterns to 47dda4e: Updated pattern-library to b7df4c0: Fix fragment on page load when using ToggleableCaption

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/262/ which resulted in this pull request.
> Updated elife/patterns to f30aded: Updated pattern-library to 0b4706a: Inline SVG hover social icons (icon files retained for reference)

- composer.json
- composer.lock
> Add SncRedisBundle

- composer.json
- composer.lock
- src/ViewModel/Converter/FormViewConverter.php
Implements https://github.com/elifesciences/patterns-php/pull/489
Note that the `composer.lock` file change is to use the current head of the feature branch in https://github.com/elifesciences/patterns-php/pull/489; this may need to be updated before merging.
> ELPP-3130 Improve form messaging

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/266/ which resulted in this pull request.
> Updated elife/patterns to 658b5b3: Updated pattern-library to 4f75dee: Delete obsolete files

- src/ViewModel/Converter/InterviewSecondaryTeaserConverter.php
Don't think there's a reason why it was excluded.
> Add image to interview secondary teaser

- src/Controller/LabsController.php
- test/Controller/LabsControllerTest.php
* Update Labs impact statement text to include CTA to sign up for tech newsletter with link (external, crm).
* Update test statements to include amended text.
> ELPP-3161 Update Labs impact statement to include tech newsletter

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/269/ which resulted in this pull request.
> Updated elife/patterns to 1ccbb02: Updated pattern-library to 252435a: Fix p elements in author details

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/271/ which resulted in this pull request.
> Updated elife/patterns to e4df86b: Updated pattern-library to 8c622c8: Keep overlay when scrolling

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/275/ which resulted in this pull request.
> Updated elife/patterns to baf03a3: Updated pattern-library to e91539b: Use real URI in login control

- composer.lock
I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/276/ which resulted in this pull request.
> Updated elife/patterns to ebd03f7: Updated pattern-library to c6da8d7: Refactor css

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/280/display/redirect which resulted in this pull request.
> Updated elife/patterns to 0373621: Updated pattern-library to 58357ad: Line height mixin

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/281/display/redirect which resulted in this pull request.
> Updated elife/patterns to 9f05b26: Updated pattern-library to be20379: [WIP] ELPP-3250 elife-utils.js tests

- app/Resources/views/base.html.twig
- app/Resources/views/page.html.twig
- app/Resources/views/status.html.twig
The status page misses `html@lang`, so my Chrome is trying to translate it from Polish. This extracts a base HTML template.
> Create base HTML template

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/284/display/redirect which resulted in this pull request.
> Updated elife/patterns to 8f46f53: Updated pattern-library to 1723172: Remove vertical padding from wrapper

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/285/display/redirect which resulted in this pull request.
> Updated elife/patterns to 1d89b84: Updated pattern-library to d8771f7: ELPP-2835 Apply baseline grid to form elements

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/288/display/redirect which resulted in this pull request.
> Updated elife/patterns to 5dd3e74: Updated pattern-library to 967b00a: Fix placement of menu close icon

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/289/display/redirect which resulted in this pull request.
> Updated elife/patterns to 477344c: Updated pattern-library to 861a8a1: Add left padding to article-download-links-list

- app/Resources/views/page.html.twig
- gulpfile.js
> Add SVG favicon

- composer.json
- composer.lock
- src/Helper/Callback.php
- src/ViewModel/Converter/ProfileContentHeaderProfileConverter.php
- test/Helper/CallbackTest.php
Adds https://github.com/elifesciences/api-sdk-php/pull/169.
> Handle profile access control change

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/290/display/redirect which resulted in this pull request.
> Updated elife/patterns to fdf52a6: Updated pattern-library to 3ea7232: Fix pull-quote spacing

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/294/display/redirect which resulted in this pull request.
> Updated elife/patterns to 3510675: Updated pattern-library to 816f038: Use getElementById() where possible

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/295/display/redirect which resulted in this pull request.
> Updated elife/patterns to 130361c: Updated pattern-library to 398448a: Stop audio player failing to initialise on fast media load

- check_critical_css.sh
- critical-css.json
- gulpfile.js
To be used from the formula after the related `gulp` command completes to cross-check if the generation has been successful.
> Smoke test for critical css

- src/Controller/ArticleTypesController.php
#377 made the content types all title case, but the pagination wasn't updated.
> ELPP-3124 Keep title case when browsing a content type

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/301/display/redirect which resulted in this pull request.
> Updated elife/patterns to 946ba38: Updated pattern-library to b8c1b62: Fix spacing above a list of About-section profiles

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/302/display/redirect which resulted in this pull request.
> Updated elife/patterns to fbf86c2: ELPP-3284 Annotation listing

- project_tests.sh
> Temporarily disable Tenon

- app/Resources/views/job-advert.html.twig
- src/Controller/JobAdvertsController.php
- test/Controller/JobAdvertControllerTest.php
> Test job advert pages

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/306/display/redirect which resulted in this pull request.
> Updated elife/patterns to ac3ea75: Updated pattern-library to 150631a: ELPP-3373 Expand article sections for annotations

- src/Controller/LabsController.php
- test/Controller/LabsControllerTest.php
Changed second sentence to be CTA for sprint applications. Change
intended as temporary, to be reverted back to commented out line on
March 5.
Text change reflected in test.
> [ELPP-3407] Update Labs impact statement

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/313/display/redirect which resulted in this pull request.
> Updated elife/patterns to e37ea64: Updated pattern-library to 7ebb922: Expand article section via click on view selector

- app/Resources/views/page.html.twig
- composer.lock
I will submit an accompanying PR on [pattern-library](https://github.com/elifesciences/pattern-library/blob/7ebb922fbbbbc6a1d10bcd4f463070efbdcc0e0b/assets/js/components/FragmentHandler.js#L79) to open all the panes.
> Allow annotation pane to be opened by default

- app/Resources/views/article-text.html.twig
- app/Resources/views/page.html.twig
- src/Helper/ModelName.php
- test/Helper/ModelNameTest.php
> ELPP-3412 Add item details to Google Tag Manager data layer

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/318/display/redirect which resulted in this pull request.
> Updated elife/patterns to 3d03769: ELPP-2643 Update URL properties default value

- smoke_tests.sh
- status_test.sh
Since these fail often, give them one more chance in case the timeout of a backend is temporary
> Retry status checks

- app/config/config_test.yml
- app/config/parameters.yml.dist
- app/config/services.yml
- app/config/services_test.yml
- src/Controller/AboutController.php
- src/Controller/SubjectsController.php
- src/DependencyInjection/GuzzleMiddlewarePass.php
- src/Guzzle/SubjectRewritingMiddleware.php
- test/Controller/HomeControllerTest.php
- test/Controller/SubjectControllerTest.php
- test/Guzzle/SubjectRewritingMiddlewareTest.php
Tries to replace mentions of a subject with another at the HTTP layer (_after_ caching).
> ELPP-3430 Rewrite subjects

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/321/display/redirect which resulted in this pull request.
> Updated elife/patterns to acf8a2b: Updated pattern-library to e54a57b: ELPP-3362 Footer icon update

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/322/display/redirect which resulted in this pull request.
> Updated elife/patterns to 5be4221: Updated pattern-library to fab42a6: ELPP-3044 Improve profile popups

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/323/display/redirect which resulted in this pull request.
> Updated elife/patterns to 3eb8b6c: Updated pattern-library to 5d36bf6: ELPP-3332 Reposition respective articles' Hypothesis affordances

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/325/display/redirect which resulted in this pull request.
> Updated elife/patterns to edd290c: Updated pattern-library to 5d63c5e: Reduce overlay on hero images

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/330/display/redirect which resulted in this pull request.
> Updated elife/patterns to 322a84f: Updated pattern-library to 693f185: ELPP-3478 Expand article sections

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/331/display/redirect which resulted in this pull request.
> Updated elife/patterns to ada2feb: Updated pattern-library to 118ed2d: Update content header links

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/332/display/redirect which resulted in this pull request.
> Updated elife/patterns to 5639efe: Updated pattern-library to 0e057bd: PI-640 Fix figure asset links when hidden

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/333/display/redirect which resulted in this pull request.
> Updated elife/patterns to ae05d49: Updated pattern-library to edeb36f: Improve button collection margins

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/336/display/redirect which resulted in this pull request.
> Updated elife/patterns to 0a895aa: Updated pattern-library to c590c16: Grid listing css grid

- src/Controller/LabsController.php
- test/Controller/LabsControllerTest.php
> Revert Labs impact statement change

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/337/display/redirect which resulted in this pull request.
> Updated elife/patterns to aabd017: Updated pattern-library to eca1566: Fix spurious listings gutter indentation

- .php_cs
Note this will block new builds until merged.
> ELPP-3163 Upgrade .php_cs to proofreader 0.2

- .php_cs
- bin/console
#915 accidentally unset the finder.
> Fix PHP-CS-Fixer finder

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/346/display/redirect which resulted in this pull request.
> Updated elife/patterns to 8a43b8f: Add Reddit title

- composer.lock
- test/Controller/ArticleControllerTest.php
- test/Controller/ArticleFiguresControllerTest.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/348/display/redirect which resulted in this pull request.
> Updated elife/patterns to e30302f: Updated pattern-library to ece34fa: ELPP-3573 Resolve content header list wrapping

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/351/display/redirect which resulted in this pull request.
> Updated elife/patterns to 7696fee: Fix pattern-library update summary

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/352/display/redirect which resulted in this pull request.
> Updated elife/patterns to 374595c: Updated pattern-library to 3265b0e321ea07b3af86330968ec617c48dad4b0

- README.md
- composer.json
- composer.lock
- src/AppKernel.php
We only use this for the Composer scripts, but this will conflict with Docker.
Requires a formula update first.
> ELPP-3323 Remove SensioDistributionBundle

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/353/display/redirect which resulted in this pull request.
> Updated elife/patterns to 9064495: Match pattern library

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/355/display/redirect which resulted in this pull request.
> Updated elife/patterns to 26e40a5: Match pattern library

- composer.lock
- test/Controller/ArticleControllerTest.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/357/display/redirect which resulted in this pull request.
> Updated elife/patterns to 09f3391: ELPP-3404: Hypothesis loading state indicators

- test/Twig/HypothesisTokenExtensionTest.php
Fixes https://github.com/elifesciences/journal/pull/940#issuecomment-387379703.
Not sure why we're only just seeing it.
> Make HypothesisTokenExtensionTest::it_generates_a_token() time sensitive

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/358/display/redirect which resulted in this pull request.
> Updated elife/patterns to e713698: Updated pattern-library to 80da34f: Increase Hypothesis load timeout to 20s

- web/app_ci.php
- web/app_continuumtest.php
- web/app_continuumtestpreview.php
- web/app_demo.php
- web/app_dev.php
- web/app_end2end.php
- web/app_preview.php
- web/app_prod.php
- web/app_test.php
Follow-up to #954. Depends on https://github.com/elifesciences/journal-formula/pull/56.
> Remove redundant front controllers

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/360/display/redirect which resulted in this pull request.
> Updated elife/patterns to 1f4aabe: Updated pattern-library to cb7a4cc: Tighten js

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/362/display/redirect which resulted in this pull request.
> Updated elife/patterns to 57babf2: Updated pattern-library to bfe45ca: Increase Hypothesis loading timeout to 1 minute

- app/Resources/views/page.html.twig
- app/config/config.yml
- app/config/parameters.yml.dist
- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/364/display/redirect which resulted in this pull request.
> Updated elife/patterns to 0fa86cf: Updated pattern-library to 11351d5: ELPP-3654: Cookie consent overlay

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/365/display/redirect which resulted in this pull request.
> Updated elife/patterns to 68b514a: Updated pattern-library to 5a524e6: Fix cookie path bug

- bin/console
- web/app.php
Relates to https://github.com/elifesciences/journal-formula/pull/60.
> Restore umask

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/368/display/redirect which resulted in this pull request.
> Updated elife/patterns to ab0d6c4: Updated pattern-library to 6c7bdb7: Turn carousel switches into perfect circles

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/370/display/redirect which resulted in this pull request.
> Updated elife/patterns to 2fd3a7b: Updated pattern-library to f135dc0: ELPP-3626: Update web fonts

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/371/display/redirect which resulted in this pull request.
> Updated elife/patterns to 04f2d62: Updated pattern-library to 6e63e98: Fix positioning of last nav-secondary__item

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/373/display/redirect which resulted in this pull request.
> Updated elife/patterns to 7f9e38c: Updated pattern-library to 29d98d7: Site header layout improvements

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/376/display/redirect which resulted in this pull request.
> Updated elife/patterns to c8da36d: Updated pattern-library to d27c4e4: Inline SocialLinks SVGs

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/377/display/redirect which resulted in this pull request.
> Updated elife/patterns to e1f70fa: Updated pattern-library to 3e59a1f: ELPP-3685 Improve hidden content and Hypothesis

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/381/display/redirect which resulted in this pull request.
> Updated elife/patterns to ea15cbe: Updated pattern-library to 5d97c41: Avoid wrapping see more links

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/382/display/redirect which resulted in this pull request.
> Updated elife/patterns to a00d48d: Updated pattern-library to bea81b1: Avoid exception inception

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/384/display/redirect which resulted in this pull request.
> Updated elife/patterns to 28b08d9: Updated pattern-library to 8e0e701: Edge site header fix

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/386/display/redirect which resulted in this pull request.
> Updated elife/patterns to 5cef22b: Updated pattern-library to d64d27b: Merge pull request #895 from elifesciences/master

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/390/display/redirect which resulted in this pull request.
> Updated elife/patterns to 613cc89: Updated pattern-library to b2b196e: Fix non-js Highlights layout

- .docker/nginx-default.conf
- .env
- docker-compose.yml
Implements https://github.com/elifesciences/journal/pull/1024#discussion_r203344826.
> Allow API to be changed

- composer.lock
- features/bootstrap/DigestContext.php
- features/bootstrap/MagazineContext.php
- test/Controller/DigestControllerTest.php
To complete https://github.com/elifesciences/jira-import/issues/4356
> Update API SDK to get digests stage feature

- features/bootstrap/MagazineContext.php
- features/magazine-digests.feature
- src/Controller/DigestsController.php
- src/Controller/MagazineController.php
- test/Controller/DigestsControllerTest.php
- test/Controller/MagazineControllerTest.php
> Update digests text

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/396/display/redirect which resulted in this pull request.
> Updated elife/patterns to c3dc91e: Updated pattern-library to 8742d5d: Add aria label to Investor Logo's for accessibility.

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/397/display/redirect which resulted in this pull request.
> Updated elife/patterns to 0bfabaf: Updated pattern-library to 0e71b5b: Aid display of longer titles in graphical headers

- src/Controller/ArticlesController.php
- test/Controller/ArticleControllerTest.php
For https://github.com/elifesciences/issues/issues/54.
> Break up editors/reviewers into separate sections

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/398/display/redirect which resulted in this pull request.
> Updated elife/patterns to 9d63c76: Updated pattern-library to 886d377: Add aria-label to Social Media in footer for Accessibility

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/402/display/redirect which resulted in this pull request.
> Updated elife/patterns to b37991d: Updated pattern-library to 320ce80: Add aria label for list of authors

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/403/display/redirect which resulted in this pull request.
> Updated elife/patterns to 666ab56: change backgrounds for annotations

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/405/display/redirect which resulted in this pull request.
> Updated elife/patterns to 69e17e1: Updated pattern-library to c04813e: Digest spacing and sample

- src/Controller/DigestsController.php
- test/Controller/DigestsControllerTest.php
For https://github.com/elifesciences/issues/issues/4422
> Update wordings of digest channel removing `the`s, using journal name

- composer.lock
- test/Controller/ArticleControllerTest.php
- test/Controller/ArticleFiguresControllerTest.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/408/display/redirect which resulted in this pull request.
> Updated elife/patterns to be9a3ff: Updated pattern-library to fcaedc1: Add aria label for contextual data

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/409/display/redirect which resulted in this pull request.
> Updated elife/patterns to 2aae023: Updated pattern-library to 04069d8: aria label for ORCID ID's

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/410/display/redirect which resulted in this pull request.
> Updated elife/patterns to 33c39f3: Updated pattern-library to 8da4578: Bug Fix for Reset Button

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/413/display/redirect which resulted in this pull request.
> Updated elife/patterns to 94b80ed: Updated pattern-library to 006b906: Aria expanded collapsible content

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/415/display/redirect which resulted in this pull request.
> Updated elife/patterns to d231c77: Updated pattern-library to 10f3b41: Increase full-width teaser image breakpoint

- src/ViewModel/Factory/SiteHeaderFactory.php
Requires https://github.com/elifesciences/patterns-php/pull/668/files
> Add id to 'Submit my Research' button

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/416/display/redirect which resulted in this pull request.
> Updated elife/patterns to 795a205: Updated pattern-library to 29afdbf: Aria main menu accessibility

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/421/display/redirect which resulted in this pull request.
> Updated elife/patterns to f8fffdc: Updated pattern-library to 3637b9a: Add GitHub link

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/423/display/redirect which resulted in this pull request.
> Updated elife/patterns to 4d77cf4: Updated pattern-library to 56e1811: Add aria-expanded, hidden and focus

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/424/display/redirect which resulted in this pull request.
> Updated elife/patterns to b07fe82: Updated pattern-library to a6cc15b: Remove width to make image 100% width

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/425/display/redirect which resulted in this pull request.
> Updated elife/patterns to fa73664: Updated pattern-library to ed84a4c: Popup color fix

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/427/display/redirect which resulted in this pull request.
> Updated elife/patterns to a598485: Updated pattern-library to 420ab90: Amend focus colour

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/429/display/redirect which resulted in this pull request.
> Updated elife/patterns to f91b9ac: Updated pattern-library to 2056783: Left align content in author popup

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/430/display/redirect which resulted in this pull request.
> Updated elife/patterns to f2ceb4d: Updated pattern-library to 033f9f9: js fix on pop up

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/431/display/redirect which resulted in this pull request.
> Updated elife/patterns to 25d192f: Add new 'warning' type to InfoBar

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/432/display/redirect which resulted in this pull request.
> Updated elife/patterns to 6f77e70: Updated pattern-library to 4aedd79: Underline links in info bars

- src/Controller/AboutController.php
Improves: https://github.com/elifesciences/issues/issues/4718
> List Founding Editor-in-Chief in Leadership section

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/435/display/redirect which resulted in this pull request.
> Updated elife/patterns to 4075577: Updated pattern-library to 9aad94a: Remove left padding from info bar when no icon

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/437/display/redirect which resulted in this pull request.
> Updated elife/patterns to 80d64b0: Updated pattern-library to bd1240f: Bug fix for hidden text showing on copy and paste

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/438/display/redirect which resulted in this pull request.
> Updated elife/patterns to 28c80b2: Updated pattern-library to 17bb98c: Call to action updates

- smoke_tests.sh
For https://github.com/elifesciences/journal-formula/pull/89
> Retry /status in smoke tests 3 times, waiting 5 seconds

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/441/display/redirect which resulted in this pull request.
> Updated elife/patterns to 2327951: Updated pattern-library to 9cdbfeb: Set font in CallToAction

- composer.lock
Addresses failures in https://alfred.elifesciences.org/blue/organizations/jenkins/test-journal/detail/test-journal/1685/pipeline
> Upgrade vulnerable symfony/symfony 3.4.20

- Jenkinsfile
- Jenkinsfile.prod
Part of https://github.com/elifesciences/issues/issues/3676
Not pushing on pull requests as not necessary yet.
> Push image when on mainline

- Jenkinsfile.update-patterns-php
- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/448/display/redirect which resulted in this pull request.
> Updated elife/patterns to ed0663a: Pass last commit message to update of patterns-php

- src/Controller/ResourcesController.php
- test/Controller/ResourcesControllerTest.php
For https://github.com/elifesciences/issues/issues/4923
> Updates to resources page

- Dockerfile
Helps in delegating some of the smoke testing to the image rather than reinventing it
> Add HEALTHCHECK

- Jenkinsfile
Slashes are not allowed.
See https://github.com/elifesciences/journal/pull/1161 which [failed](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fjournal/detail/PR-1161/2/pipeline/).
> Sanitize Docker image tag

- src/Controller/PrivacyController.php
This is in relation to task #5010
> Additional privacy policy content

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/453/display/redirect which resulted in this pull request.
> Updated elife/patterns to 2c43659: Updated pattern-library to dddb65b: Amend Curated to Edited

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/454/display/redirect which resulted in this pull request.
> Updated elife/patterns to 5b9a1cb: Updated pattern-library to 57bca85: page views on charts/metrics bug

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/455/display/redirect which resulted in this pull request.
> Updated elife/patterns to 97b63c6: Updated pattern-library to 9874d46: Amend so div does not fit 100% of content header

- Jenkinsfile
Came up in https://github.com/elifesciences/issues/issues/5222
Reflects what the pipeline is doing.
> Rename test-journal stage

- .docker/parameters.yml
- app/config/parameters.yml.dist
- composer.json
- composer.lock
- src/Controller/ArticlesController.php
- test/Controller/ArticleControllerTest.php
For https://github.com/elifesciences/issues/issues/5277
Depends on https://github.com/elifesciences/journal-formula/pull/107
> Implement articles dismissible infobars

- app/Resources/views/page.html.twig
- composer.lock
Prevents the brief display on page load of an info bar that has previously been dismissed.
> Prevent flash of dismissed info bar

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/460/display/redirect which resulted in this pull request.
> Updated elife/patterns to ef59661: Updated pattern-library to baedee4: Centre author list collapse affordance on narrow viewports

- .docker/parameters.yml
- app/config/config_ci.yml
- app/config/parameters.yml.dist
- src/Controller/ArticlesController.php
For https://github.com/elifesciences/issues/issues/5344
Depends on https://github.com/elifesciences/journal-formula/pull/109 having been applied everywhere.
> Rename configuration to example_rds_articles

- .docker/parameters.yml
- app/config/config_ci.yml
- app/config/parameters.yml.dist
- src/Controller/ArticlesController.php
- src/ViewModel/Converter/ArticleDownloadLinksListConverter.php
- test/Controller/ArticleControllerTest.php
https://github.com/elifesciences/issues/issues/5346
> Add RDS download link

- src/ViewModel/Converter/ArticleDownloadLinksListConverter.php
- test/Controller/ArticleControllerTest.php
https://github.com/elifesciences/issues/issues/5403
> Add 'Learn more about DAR' link

- app/Resources/views/article-rds.html.twig
- composer.json
- composer.lock
- src/Controller/ArticlesController.php
- test/Controller/ArticleControllerTest.php
https://github.com/elifesciences/issues/issues/5402
> Add executable code link to the view selector

- app/Resources/views/article-rds.html.twig
- test/Controller/ArticleRdsControllerTest.php
https://github.com/elifesciences/issues/issues/5415
> Add canonical link and noindex directive to RDS companion pages

- app/config/services.yml
- composer.json
- composer.lock
- src/ViewModel/Converter/ArticleTeaserConverter.php
- test/ViewModel/Converter/ArticleTeaserConverterTest.php
- test/ViewModel/Converter/ModelConverterTestCase.php
https://github.com/elifesciences/issues/issues/5416
> Change article teaser formats when an RDS companion is available

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/465/display/redirect which resulted in this pull request.
> Updated elife/patterns to f99e114: Updated pattern-library to 0ac3fc4: Align teaser formats to the right

- app/config/routing.yml
- test/Controller/ArticleRdsControllerTest.php
https://github.com/elifesciences/issues/issues/5426
> Update RDS companion page path

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/466/display/redirect which resulted in this pull request.
> Updated elife/patterns to e72ea92: Updated pattern-library to 3969353: Amend class name

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/467/display/redirect which resulted in this pull request.
> Updated elife/patterns to edd849c: Updated pattern-library to 3f5d376: Change flickr url

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/469/display/redirect which resulted in this pull request.
> Updated elife/patterns to baa9453: Updated pattern-library to 9a9573d: Change logos for journal with new branding

- gulpfile.js
- npm-shrinkwrap.json
- package.json
@thewilkybarkid This is what has happened when I npm uninstalled the gulp-svg2png package. Do I need to do anything else?
> Uninstalled gulp-svg2png package

- src/Helper/ModelName.php
- test/Helper/ModelNameTest.php
This should fix the following issue: https://github.com/elifesciences/issues/issues/5605
> Support promotional collection model in gtm

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/470/display/redirect which resulted in this pull request.
> Updated elife/patterns to 0e2c939: Updated pattern-library to 4b27ccf: Fix so links can be clicked in popup

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/471/display/redirect which resulted in this pull request.
> Updated elife/patterns to 5df3cb5: Updated pattern-library to 39deb57: Add left aligned in popup for author details.

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/472/display/redirect which resulted in this pull request.
> Updated elife/patterns to 52ced61: Updated pattern-library to ac96184: Refactor for accessibility to work for screen readers

- Jenkinsfile
This reverts commit 1594435b0f96bbe3d1f3dabc6b39d0fd1c455a3b.
> Revert "Temporarily remove continuumtest and continuumtestpreview from automated deployment (#1265)"

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/473/display/redirect which resulted in this pull request.
> Updated elife/patterns to 539feec: Updated pattern-library to 42db14d: Add Tweet block

- composer.lock
- src/ViewModel/Converter/Block/YouTubeConverter.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/474/display/redirect which resulted in this pull request.
> Updated elife/patterns to 561e5d0: Updated pattern-library to 1a8e5c7: Add optional title attribute to iframe

- src/Controller/SubmitController.php
related to libero/reviewer#625
moved up the return url check before user authentication
> moved return url check before is user authenticated check

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/477/display/redirect which resulted in this pull request.
> Updated elife/patterns to 8f93082: Updated pattern-library to f09d475: Personalised cover styling

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/478/display/redirect which resulted in this pull request.
> Updated elife/patterns to 42f60da: Updated pattern-library to 8557b4f: Accessibility changes phase2

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/483/display/redirect which resulted in this pull request.
> Updated elife/patterns to fd2f47d: Updated pattern-library to 0fa664c: Jump menu expanded

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/487/display/redirect which resulted in this pull request.
> Updated elife/patterns to 90338de: Updated pattern-library to 3a83e99: Add overflow-anchor to stop bug in Chrome

- src/ViewModel/Converter/ArticleDownloadLinksListConverter.php
This will allow us to remove the redirect on https://elifesciences.org/labs/7dbeb390
> Update labs post link

- app/Resources/views/page.html.twig
We shouldn't merge this in until after this change to pattern-library comes through to journal: https://github.com/elifesciences/pattern-library/pull/1016
> Remove hypothesis services icon (#1324)

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/491/display/redirect which resulted in this pull request.
> Updated elife/patterns to a5a1894: Updated pattern-library to 451c551: Remove text-transform

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/493/display/redirect which resulted in this pull request.
> Updated elife/patterns to 0b2bfd1: Personalised cover download updates

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/496/display/redirect which resulted in this pull request.
> Updated elife/patterns to f8f7a72: Updated pattern-library to d866f52: Make title changeable

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/498/display/redirect which resulted in this pull request.
> Updated elife/patterns to 286f0a0: Updated pattern-library to 4cf7451: adding classes for GTM to pick up

- app/Resources/views/subject.html.twig
- app/config/routing.yml
- test/Controller/SubjectControllerTest.php
This should not be merged in until after: https://github.com/elifesciences/journal-formula/pull/131
> Introduce link rel=alternate for subject specific rss feed

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/500/display/redirect which resulted in this pull request.
> Updated elife/patterns to e8c2e1e: Updated pattern-library to 8ffd3d0: Speech bubble redesign - wrapped with prefix

- .docker/parameters.yml
- app/config/config_ci.yml
- app/config/parameters.yml.dist
- app/config/services.yml
- src/Controller/SubmitController.php
- src/Security/SubmissionTokenGenerator.php
- src/ViewModel/Factory/SiteHeaderFactory.php
- test/Controller/SubmitControllerTest.php
- test/Security/SubmissionTokenGeneratorTest.php
- test/ViewModel/Factory/SiteHeaderFactoryTest.php
naive removal of all mentions of `xpub`
`XpubTokenGenerator` has been renamed `SubmissionTokenGenerator`
`xpub_client_id` and `xpub_client_secret` have been renamed `submission_client_id` and `submission_client_secret`
> xpub removal

- .docker/parameters.yml
- app/config/config_ci.yml
- app/config/parameters.yml.dist
- app/config/services.yml
- src/Controller/SubmitController.php
- src/Security/XpubTokenGenerator.php
- src/ViewModel/Factory/SiteHeaderFactory.php
- test/Controller/SubmitControllerTest.php
- test/Security/XpubTokenGeneratorTest.php
- test/ViewModel/Factory/SiteHeaderFactoryTest.php
This reverts commit a030dc5c23c8e497bf14df5bf7f287fd2ff71f19.
> Revert "xpub removal (#1375)"

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/501/display/redirect which resulted in this pull request.
> Updated elife/patterns to c413c6a: Updated pattern-library to d8b87e8: Sort outlines in carousel

- app/Resources/views/digest.html.twig
Have left in keywords but not showing any at this time.
> Add schema for SEO improvements to Digest

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/503/display/redirect which resulted in this pull request.
> Updated elife/patterns to 10987d1: Updated pattern-library to dc2641a: Content header refactor

- app/Resources/views/magazine.html.twig
- app/config/routing.yml
- test/Controller/MagazineControllerTest.php
Before merging this in we must deploy https://github.com/elifesciences/journal-formula/pull/136 and verify that it is working.
> Add magazine rss link

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/504/display/redirect which resulted in this pull request.
> Updated elife/patterns to 4001812: Updated pattern-library to 3d21141: fix for current press packs issue

- .docker/parameters.yml
- app/Resources/views/page.html.twig
- app/config/config.yml
This reverts commit 3ae4b297d9f0074e89c41c7d491957c29434af55.
> Revert "Add Google Optimize code (#1395)"

- .docker/parameters.yml
- app/config/config_ci.yml
- app/config/parameters.yml.dist
- app/config/services.yml
- src/Controller/SubmitController.php
- src/Security/XpubTokenGenerator.php
- src/ViewModel/Factory/SiteHeaderFactory.php
- test/Controller/SubmitControllerTest.php
- test/Security/XpubTokenGeneratorTest.php
- test/ViewModel/Factory/SiteHeaderFactoryTest.php
This reverts commit d73fd12d35375b883f6f36a474d308005a934843.
> Revert "Revert "Revert "xpub removal (#1375)" (#1390)" (#1394)"

- README.md
- src/Controller/AboutController.php
Updated the text on the about peer-review page as per the new spec from the comms team.
This resolves elifesciences/issues#6297
> chore: update about peer-review with new text

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/506/display/redirect which resulted in this pull request.
> Updated elife/patterns to 60cb37f: Updated pattern-library to 975b691: upating aria roles for investor logo

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/507/display/redirect which resulted in this pull request.
> Updated elife/patterns to 030b08b: Updated pattern-library to f164f3c: Add CSS to add backup for image attribution

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/508/display/redirect which resulted in this pull request.
> Updated elife/patterns to c57828f: Updated pattern-library to d4b8574: Refactor for fix

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/509/display/redirect which resulted in this pull request.
> Updated elife/patterns to 4ef32e2: Updated pattern-library to 491f85e: Add screen width detection for collapsible sections on articles

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/514/display/redirect which resulted in this pull request.
> Updated elife/patterns to 107e7c9: Updated pattern-library to b25d767: Hypothesis CTA at end of article for inside-elife, interview and press-package

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/515/display/redirect which resulted in this pull request.
> Updated elife/patterns to 33ef97b: Updated pattern-library to 3f43f08: Add CarouselItem javascript behaviour

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/516/display/redirect which resulted in this pull request.
> Updated elife/patterns to b89223f: Updated pattern-library to 480acb5: change javascript to target all collapsible sections for fragment handling

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/519/display/redirect which resulted in this pull request.
> Updated elife/patterns to 8df0de3: Updated pattern-library to 88958ed: Social Media image updates

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/520/display/redirect which resulted in this pull request.
> Updated elife/patterns to bcc49f9: Updated pattern-library to 1267b7a: About profile default image

- composer.lock
This reverts commit ca950b7d0e070f89b6681d042c6f9abc6167211f.
> Revert "Updated elife/patterns to bcc49f9: Updated pattern-library to1267b7a: About profile default image (#1452)"

- composer.lock
- src/ViewModel/Converter/PersonAboutProfileConverter.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/521/display/redirect which resulted in this pull request.
> Updated elife/patterns to d22f9d3: Updated pattern-library to 4c72f21: Allow placeholder image option on about profile

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/522/display/redirect which resulted in this pull request.
> Updated elife/patterns to 18ad763: Updated pattern-library to 9484359: Adding underline to blue links

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/524/display/redirect which resulted in this pull request.
> Updated elife/patterns to 046e41e: Updated pattern-library to bff2fc4: Amend font size for doi

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/527/display/redirect which resulted in this pull request.
> Updated elife/patterns to fb6da5d: Updated pattern-library to f1e4bc8: Non doi link styling amends

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/535/display/redirect which resulted in this pull request.
> Updated elife/patterns to ba3cfe9: Updated pattern-library to 4c2b911: Image credit issue changes

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/537/display/redirect which resulted in this pull request.
> Updated elife/patterns to d9e5164: Updated pattern-library to 2dddaa9: Add padding to list css class

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/538/display/redirect which resulted in this pull request.
> Updated elife/patterns to 44dc733: Text change for call to action button for Hypothesis

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/540/display/redirect which resulted in this pull request.
> Updated elife/patterns to cea7cb7: Updated pattern-library to 864ae0b: Add styling for Cookiebot privacy focus removal

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/543/display/redirect which resulted in this pull request.
> Updated elife/patterns to 043d5a3: Updated pattern-library to 079abec: Remove valid form field styles and examples

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/550/display/redirect which resulted in this pull request.
> Updated elife/patterns to e1a04ac: Updated pattern-library to 260a0c5: Fix IOS issue with checkboxes and refactor CSS

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/551/display/redirect which resulted in this pull request.
> Updated elife/patterns to bae3316: Updated pattern-library to bd12e1e: Sidebar navigation expanded authors list issue

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/552/display/redirect which resulted in this pull request.
> Updated elife/patterns to bc4b177: Updated pattern-library to 78f4d9f: fix: ios styling issue for checkboxes

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/554/display/redirect which resulted in this pull request.
> Updated elife/patterns to 9b14ff6: Updated pattern-library to 1b2a00b: Version change of Photoswipe to 4.1.3

- composer.lock
- src/ViewModel/Factory/SiteHeaderFactory.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/556/display/redirect which resulted in this pull request.
> Updated elife/patterns to 4642284: Updated pattern-library to 88ac499: Allow site-header-title to have simpler variants

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/559/display/redirect which resulted in this pull request.
> Updated elife/patterns to 9c845b8: Updated pattern-library to a56f41d: Carbon neutral logo footer addition

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/563/display/redirect which resulted in this pull request.
> Updated elife/patterns to 2b347cc: Updated pattern-library to 6edb571: Table list indentation issue

- composer.lock
- src/ViewModel/Converter/ArticleDownloadLinksListConverter.php
- test/Controller/ArticleControllerTest.php
- test/Controller/ArticleFiguresControllerTest.php
- test/Controller/PageTestCase.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/576/display/redirect which resulted in this pull request.
> Updated elife/patterns to 9535826: Updated pattern-library to 8a573f4: Allow for intro in download links

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/578/display/redirect which resulted in this pull request.
> Updated elife/patterns to abab388: Updated elife/patterns to abab388: Updated pattern-library to deb3368: Remove color from reference__title

- composer.lock
- src/ViewModel/Converter/ArticleDownloadLinksListConverter.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/580/display/redirect which resulted in this pull request.
> Updated elife/patterns to 8964ddf: Updated pattern-library to 0624693: Allow PMC check before displaying ReadCube link

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/581/display/redirect which resulted in this pull request.
> Updated elife/patterns to 30543c4: Updated pattern-library to 8502b5d: Fix side navigation on bottom of page

- composer.lock
- src/Controller/AboutController.php
- src/Controller/AlertsController.php
- src/Controller/ArticlesController.php
- src/Controller/InterviewsController.php
- src/Controller/MediaPolicyController.php
- src/Controller/PressPacksController.php
- src/Controller/PrivacyController.php
- src/Controller/ResourcesController.php
- src/Controller/TermsController.php
- src/ViewModel/Converter/Block/QuestionConverter.php
- src/ViewModel/Converter/Block/SectionConverter.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/585/display/redirect which resulted in this pull request.
> Updated elife/patterns to 3249b16: Updated pattern-library to 8ce91f4: Relax hasBehaviour dependency and handle in patterns-php

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/586/display/redirect which resulted in this pull request.
> Updated elife/patterns to 09957e3: Updated pattern-library to 2d7a293: Add examples of related item teaser with image

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/588/display/redirect which resulted in this pull request.
> Updated elife/patterns to 09a4567: Updated pattern-library to b2d4554: Related article issue

- composer.lock
- src/Controller/ArticlesController.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/603/display/redirect which resulted in this pull request.
> Updated elife/patterns to 7491523: Updated pattern-library to cf304f1: styling counters for views and citations

- src/Controller/ArticlesController.php
- test/Controller/ArticleFiguresControllerTest.php
Ref: elifesciences/issues#7436
> Redirect figures page for editorial and insight content

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/610/display/redirect which resulted in this pull request.
> Updated elife/patterns to 8d93982: Updated pattern-library to 7a32457: Removing as causing weird issues with links

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/620/display/redirect which resulted in this pull request.
> Updated elife/patterns to 29b8907: Updated pattern-library to 92a59af: Reformat status and date in teaser

- app/Resources/views/home.html.twig
- app/Resources/views/page.html.twig
- composer.lock
- src/Controller/HomeController.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/626/display/redirect which resulted in this pull request.
> Updated elife/patterns to be7b406: Updated pattern-library to 5e6c598: Update MSA picker + remove strapline

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/627/display/redirect which resulted in this pull request.
> Updated elife/patterns to eb720ff: Updated pattern-library to 8dd00bb: Reduce space at top of newer content headers and new menu.

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/629/display/redirect which resulted in this pull request.
> Updated elife/patterns to 37e08a4: Updated pattern-library to f1e896a: Hero banner and highlights changes

- app/Resources/views/home.html.twig
- app/config/config.yml
- app/config/config_dev.yml
- app/config/config_preview.yml
- features/archive.feature
- features/bootstrap/HomepageContext.php
- features/homepage-hero.feature
- src/Controller/HomeController.php
@smoqadam this should break tests. I would just focus on fixing/refactoring the tests rather than removal of carousel.
> Enable feature_hero on all instances of journal

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/633/display/redirect which resulted in this pull request.
> Updated elife/patterns to 8129775: Updated pattern-library to d98a986: Revert "Adjust style of dismissible info bar" (#903)

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/635/display/redirect which resulted in this pull request.
> Updated elife/patterns to 3e18633: Updated pattern-library to 07c8e82: Reintroduce new styles with dismissible info bar with fix for close button

- composer.lock
- src/Controller/ArticlesController.php
This PR just updates patterns without introducing new behaviour so that we can be unblocked from journal releases while we work on introducing ViewSelector to the home and MSA pages.
> Adapt ViewSelector to handle new parameter isTabSelector

- docker-compose.override.yml
The syntax used was causing the error for the update pipeline. This should fix it.
> Modified volumes in docker-compose.override

- src/Controller/ArticlesController.php
Changed text from "from early next year" to "from January 2023"
> Updated info bar text on article pages

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/663/display/redirect which resulted in this pull request.
> Updated elife/patterns to d288365: Updated pattern-library to 13d4221: remove position relative

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/666/display/redirect which resulted in this pull request.
> Updated elife/patterns to 6f0a8aa: Updated pattern-library to 6805778: Revert "remove position relative" (#956)

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/669/display/redirect which resulted in this pull request.
> Updated elife/patterns to bd3700f: Add Content aside title length

- composer.lock
- features/bootstrap/SearchContext.php
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/671/display/redirect which resulted in this pull request.
> Updated elife/patterns to c87a4c6: Updated pattern-library to 9c0ec2e: Adjust Related item margin

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/673/display/redirect which resulted in this pull request.
> Updated elife/patterns to 06a1015: Updated pattern-library to df6a1e0: Add aria-label for Timeline links

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/677/display/redirect which resulted in this pull request.
> Updated elife/patterns to bee251d: Updated pattern-library to 7764656: refactor on max-width to rems so changes at 729px and not 730

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/730/display/redirect which resulted in this pull request.
> Updated elife/patterns to c87cd2f: Updated pattern-library to a391042: Change Copyright link

- src/Controller/WhoWeWorkWithController.php
- test/Controller/WhoWeWorkWithControllerTest.php
Re issue https://github.com/elifesciences/issues/issues/8585
Since you found this @lsh-0, if you feel qualified to review and merge it I'm adding you as a reviewer.
> Change JATS4R URL in Who We Work With.

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/743/display/redirect which resulted in this pull request.
> Updated elife/patterns to 72b98fb: Updated pattern-library to a7b0700: Adjust z-index so tabbed navigation does not show when search overlay appears

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/746/display/redirect which resulted in this pull request.
> Updated elife/patterns to 11f6805: Updated pattern-library to 6ae6d67: fix: Due to cropping issue

- app/Resources/views/page.html.twig
No longer needed as we do not support IE9 and below
> remove html5shiv

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/771/display/redirect which resulted in this pull request.
> Updated elife/patterns to 09ee44d: Updated pattern-library to 9dc4923: Change eLife address

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/773/display/redirect which resulted in this pull request.
> Updated elife/patterns to d33a75b: Updated pattern-library to 66bcf48: Update bullet points

- composer.lock
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/788/display/redirect which resulted in this pull request.
> Updated elife/patterns to 4cfcd1f: Updated pattern-library to efef5f6: Add doi distance

- docker-compose.yml
> Use API_URL as fallback for API_URL_SEARCH_PAGE

- app/config/routing.yml
- composer.json
- composer.lock
- features/bootstrap/ArchiveContext.php
- features/bootstrap/ArticleTypeContext.php
- features/bootstrap/HomepageContext.php
- features/bootstrap/MagazineContext.php
- features/bootstrap/SearchContext.php
- features/bootstrap/SubjectContext.php
- src/Controller/ArticlesController.php
- src/Controller/SearchController.php
- src/Helper/ModelName.php
- test/Controller/ArchiveMonthControllerTest.php
- test/Controller/ArticleControllerTest.php
- test/Controller/ArticleTypeControllerTest.php
- test/Controller/AuthenticationTest.php
- test/Controller/HomeControllerTest.php
- test/Controller/MagazineControllerTest.php
- test/Controller/SearchControllerTest.php
- test/Controller/SubjectControllerTest.php
- test/Guzzle/StatusDateOverrideMiddlewareTest.php
- test/Guzzle/SubjectRewritingMiddlewareTest.php
- test/Helper/ModelNameTest.php
* Add expression of concern
* Update composer
* Add expression of concern
* Revert composer
* Change composer
* Change test
* Change test
* Update composer
* Change test
* Remove dump
* Change test
* Update elife api version
* Change case of "concern" to "Concern"
* Reverting so we can merge PR
* Revert "Merge branch 'develop' into expression-concern"
This reverts commit 84ed9e83caa51132028a8412569d3016b8a0fda2, reversing changes made to 35b7455ea48e1fc67b0c36a05dfc1362e93cf316.
* Revert "Reverting so we can merge PR"
This reverts commit 35b7455ea48e1fc67b0c36a05dfc1362e93cf316.
* update api dummy/api-sdk
* Re-apply changes from the upstream
* fix reference to search page api sdk
* Update elife/api-sdk and refactor ArticleControllerTest
* Reinstate upstream changes
---------
> Add expression of concern (#1901)

- .env
- Dockerfile.assets_builder
- docker-compose.override.yml
- docker-compose.yml
- gulpfile.js
Needed to build locally on mac M1. We have verified that it also works on the Intel mac.
> Allow Apple Silicon laptops to run journal locally

- Makefile
- lists some of the common tasks described in the README
- avoids pitfalls on clearing state e.g. after modifying `assets`, ensuring we clear Docker volumes
- provides a development cycle where a commit is made after a successful `make check`.
> Introduce a makefile

- Makefile
Clean up of tasks that we manually ran in elifesciences/issues#8927.
> Provide a make target to see production data

- src/Controller/ArticlesController.php
https://github.com/elifesciences/issues/issues/9096
> Fix error for POA on Feature Articles
