composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/206/ which resulted in this pull request.

Updated elife/patterns to c5e88e0: Updated pattern-library to 3948894: ELPP-2791 Only use MutationObserver if it's available

---

Jenkinsfile
Jenkinsfile.prod

We check we are green, but we can always override and deploy anyway if needed to fix a problem

New Relic check on production deploy

---

Jenkinsfile.prod

The minimum value can be customized with an additional parameter, the default is 0.85
Tested in https://ci--alfred.elifesciences.org/job/prod-journal/372/

Ensure APM apdex is within green limit before deploying

---

composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/215/ which resulted in this pull request.

Updated elife/patterns to 42be244: Updated pattern-library to 400a7e8: Update MathJax and use CommonHTML by default

---

composer.json
composer.lock

Adds fix from https://github.com/cocur/slugify/pull/176 before it's merged upstream.

ELPP-2904 Handle accents in slugs

---

app/config/config_prod.yml

`unsafe-inline` allows local (and injected, eg New Relic) scripts/styles to work. Also disables the HTTP->HTTPS redirect by whitelisting all paths (bit of a hack), as this broke ELB's healthcheck.

Fix NelmioSecurityBundle

---

composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/220/ which resulted in this pull request.

Updated elife/patterns to 4f97eb2: Updated pattern-library to 5efb752: Remove padding from et al link

---

api-dummy.sha1

When a project depends on the api-dummy, builder-base-formula requires it to be pinned

Pin api-dummy

---

src/AppKernel.php

A quick win to allow for environment variables to override parameters already defined in `parameters.yml`.

Allow for parameters environment variable

---

app/config/config_prod.yml
composer.json
composer.lock

If New Relic is installed, the app break when logging. This allows individual handlers to fail silently.

Allow Monolog handlers to fail

---

composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/235/ which resulted in this pull request.

Updated elife/patterns to d5c89d1: Updated pattern-library to 0485bc5: Don't try and highlight if there are no jump links

---

app/Resources/views/about-people.html.twig
app/Resources/views/archive-year.html.twig
app/Resources/views/grid/listing-one-column.html.twig
app/Resources/views/labs.html.twig
app/Resources/views/pagination-grid.html.twig
app/Resources/views/podcast.html.twig
app/Resources/views/subjects.html.twig
app/Resources/views/who-we-work-with.html.twig

Pages like https://elifesciences.org/labs?page=2 aren't currently full-width, which is wrong for grid listings.
This allows `listing-one-column.html.twig` to be full width, and is then reused by all full-width listing pages.

Make all grid pagination pages full width

---

composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/250/ which resulted in this pull request.

Updated elife/patterns to 45af736: Updated pattern-library to b873782: ELPP-3018 Add no-image placeholder graphic to archive listings

---

gulpfile.js

Fixes the broken asset paths in the critical css.
The third level of `/assets/patterns/level-to-be-raised-from-by-actual-path-double-dot/` is needed because the asset paths in the css begin `../`. This could be renamed to something better.

Fix image paths in critical css

---

Jenkinsfile

Currently the deploy is performed daily. Projects should be transitioned to immediately deploy there as soon as tests are green.
If this is too slow, we can deploy `demo` and `continuumtest` in parallel.

ELPP-1947 Deploy on continuumtest

---

src/Controller/ArticlesController.php
test/Controller/ArticleControllerTest.php

#716 applied to all pages, meaning random items were hidden on larger screens.

Only make first item related on the first page

---

src/Controller/ArticlesController.php
test/Controller/ArticleControllerTest.php

Currently makes a count request, then first page. This should halve the load on Recommendations.
(100 is far more than we need, most results is currently 13 IIRC.)

Limit Recommendations to 100

---

composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/265/ which resulted in this pull request.

Updated elife/patterns to 407c012: Updated pattern-library to 926b99b: Fix MathJax render bug in table footnotes

---

Jenkinsfile

This is not a big difference from the current set of tests, but some only targeting the API and using journal only accidentally have been excluded from the new marker.

Only run end2end tests explicitly marked for journal

---

app/config/routing.yml

two fixes escape '.' in doi
third fixes a missing leading slash

routing, fix three small typos

---

composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/268/ which resulted in this pull request.

Updated elife/patterns to 330e5ba: Updated pattern-library to 965fb0c: Stop initialising components if other patterns aren't available

---

npm-shrinkwrap.json
package.json

Looks like `npm-shrinkwrap.json` was generated with an earlier version of `npm`, so the first commit regenerates it using our standard `3.10.10`.
The second commit is the actual change, updating the `critical` module to the latest version, which uses penthouse 0.11.13. This will get some performance improvements that were introduced in penthouse 0.11.6.
We'll want to do this again once critical has been updated to use penthouse 1.x

ELPP-3223 Update module named critical

---

composer.lock

I have run http://ci--alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/274/ which resulted in this pull request.

Updated elife/patterns to 9430b9f: Updated pattern-library to f76b7bf: Use non-breaking space in ISSN

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/283/display/redirect which resulted in this pull request.

Updated elife/patterns to 654fa14: Updated pattern-library to b5e3eb9: Catch errors thrown by text-clipper library

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/286/display/redirect which resulted in this pull request.

Updated elife/patterns to 6a93838: Updated pattern-library to b9c5ef6: Use baseline grid mixins

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/287/display/redirect which resulted in this pull request.

Updated elife/patterns to 63c7eaa: Updated pattern-library to 99618cf: Prevent social media icons repeating at larger font sizes

---

composer.lock
features/bootstrap/ArticleContext.php
features/bootstrap/SearchContext.php
test/Controller/ArticleBibTexControllerTest.php
test/Controller/ArticleControllerTest.php
test/Controller/ArticleFiguresControllerTest.php
test/Controller/ArticleRisControllerTest.php
test/Controller/DoiControllerTest.php

Avoids problems when using the API Dummy (https://github.com/elifesciences/api-sdk-php/pull/168).

Update API SDK

---

src/Controller/LabsController.php

- Update URL address to include GA utm tracking. 
- This doesn't affect the test (no text change).
@giorgiosironi hi Giorgio, a simple change proposed here to update a URL.

Add campaign tracking to technews link

---

app/Resources/views/page.html.twig

The current use of `window.location.replace` causes issues with the browser history. `assign` is better.
To recreate the problem: go to the homepage, click on any article link, once on the article page open the annotation client and click the `Log in` link in the hypothesis client. Once you have been forwarded on, press back in the browser window and you will arrive at the homepage rather than the article page.
The expected behaviour is that the back button will result in the user being returned to the article page.

use window.location.assign rather than window.location.replace

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies-journal-update-patterns-php/293/display/redirect which resulted in this pull request.

Updated elife/patterns to 4a2c6e0: Updated pattern-library to b129bf7: Hook up hypothesis count even when not on an article

---

npm-shrinkwrap.json
package.json

To see if it resolves the critical-CSS problems, this upgrades Critical and Penthouse, which in turn downgrades Puppeteer/Chromium.

Update Critical and Penthouse

---

npm-shrinkwrap.json

Current critical CSS issues seem to be caused by https://github.com/websockets/ws/issues/1256 (the library had been updated in #810).

Downgrade ws

---

app/config/config.yml
test/Controller/AuthenticationTest.php

Uses the `Referer` header rather than setting a query string parameter.

ELPP-3338 Redirect to the previous page after log in

---

src/Controller/AuthController.php

#824 got through to production and broke the log-in page. Rather than be smart about trying to work out the firewall name, let's just hard-code it.

Hard-code firewall name

---

src/Controller/ArticlesController.php
test/Controller/ArticleControllerTest.php

First visible when #801 made the speech bubble part of the list of content (the `array_filter()` already existed, but I don't think it was ever used). Seems like the Mustache engine doesn't like associative arrays (since this is now missing keys).
Maybe we should always use `array_values()` inside every view model where the pattern wants an array rather than an object. /cc @davidcmoulton.

Fix view selector when Hypothesis is enabled

---

src/Controller/Controller.php
test/Controller/AuthenticationTest.php

Extracted from #852.
Bit of an older post, but https://stackoverflow.com/a/6474975/77199 suggests that we do need to `$this->get('security.token_storage')->setToken(null);` (which had been causing a test failure, but not real-world failures). Rather than worry about all that, given this is an edge-case (Profiles is broken and it's not in the cache) let's just redirect the user to the log out page instead.

Use the log-out page if a user's profile can't be loaded

---

src/Controller/ArticlesController.php
src/Controller/InterviewsController.php
src/Helper/ModelRelationship.php
src/ViewModel/Converter/ArticleRelatedItemTeaserConverter.php
src/ViewModel/Converter/CollectionRelatedItemTeaserConverter.php
src/ViewModel/Converter/ExternalArticleRelatedItemTeaserConverter.php
src/ViewModel/Converter/PodcastEpisodeChapterRelatedItemTeaserConverter.php
test/Helper/ModelRelationshipTest.php

#867 accidentally switched the default text for when two articles are related to the default _unrelated_ text.
(Probably caused by not having tests before.)

ELPP-3437 Fix related item text when articles are related

---

src/EventListener/ApiTimeoutSubscriber.php
test/EventListener/ApiTimeoutSubscriberTest.php

Currently cURL timeouts are turned into 504 responses, but a 504 response from the API becomes a 500. This keeps it as a 504 (which allows Spectrum to retry).

ELPP-3447 Return API 504 responses

---

src/Helper/CanConvertContent.php

https://elifesciences.org/articles/01948#s2-3-2-2-1 should be a `<h6>`, but the different levels get stuck as a `<h3>`.

Fix nested title levels

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/329/display/redirect which resulted in this pull request.

Updated elife/patterns to 5bdac79: Updated pattern-library to 5d017a5: Make ORCID links in ContentHeaderProfile match text colour

---

project_tests.sh
test/AppKernelTestCase.php

https://github.com/elifesciences/journal/blob/6f4a523ce29c1068f8e98f5c7845b3d9f6038d0e/test/Controller/ExceptionControllerTest.php#L9-L20
requires not using `debug` mode to check the production exception page, but it means that the cache has to be cleared before running to make sure it's using a fresh container (a service/class disappearing will break the test otherwise). Rather than rely on the test script doing it beforehand, we can recognise the case and force it (avoids the problem happening locally too).

Forcibly clear cache if test isn't using debug mode

---

src/Guzzle/SubjectRewritingMiddleware.php
test/Guzzle/SubjectRewritingMiddlewareTest.php

It disappears when content has been migrated over, so we'll need to add it.

Make sure rewritten subject exists in search results

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/338/display/redirect which resulted in this pull request.

Updated elife/patterns to 95fe655: Updated pattern-library to 940d3a6: Only use CSS grid when grid gap property is supported

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/344/display/redirect which resulted in this pull request.

Updated elife/patterns to 4865ecd: Use rawurlencode in SocialMediaSharers

---

critical-css.json

#938 broke because we forgot that it uses the API Dummy, not the real content, so these pages don't exist. /cc @davidcmoulton (@giorgiosironi Maybe we should test these...)
I've also fixed the subject which hasn't been renamed in the API Dummy, but still has the redirect applied.

ELPP-3404 Fix critical CSS

---

.ci/behat
.ci/phpunit
Dockerfile.ci
Jenkinsfile
behat.yml.dist

Everything fails, but `.ci` tasks run in parallel.
Test artifacts need some cross-check once everything runs.

ELPP-3323 Experiment with dockerComposeProjectTestsParallel

---

.env
Dockerfile.selenium
README.md
behat.yml.dist
docker-compose.ci.yml
features/bootstrap/Context.php
features/bootstrap/HomepageContext.php
src/DependencyInjection/HttpCachePass.php

#940 saw Redis used for caching rather than the filesystem, but without isolation leading to conflicts in tests. Rather than turn off Redis, this adds the kernel's instance (eg `behat1`, `phpunit2`) to the namespace.

Fix non-deterministic tests

---

docker-compose.ci.yml
docker-compose.yml

- Remove implied dependency (`assets` depends already on `cli`, which depends on `composer`)
- Add missing dependency from `ci` to `composer-dev` (causing failures such as in #980)

Revise build time Docker dependencies

---

Jenkinsfile
smoke_tests.sh
status_test.sh

The `ci` environment does not use these anymore, but deploys to end2end, continuumtest and production are currently uncovered.

ELPP-3393 Reintroduce smoke tests

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/379/display/redirect which resulted in this pull request.

Updated elife/patterns to 9d4c16a: Updated pattern-library to 427037b: Prevent popup link's default behaviour & propagation if href ends in #

---

Dockerfile.fpm
app/Resources/views/page.html.twig
app/config/config.yml
gulpfile.js
src/DependencyInjection/PreloadPass.php

Without using Containers in production there's an ordering problem, as the files are currently created after the site is initialised, so they're not present. They can be read from the source though.

Avoid using Gulp for the preload file and JS loader

---

src/ViewModel/Factory/SiteHeaderFactory.php

Makes more sense when using a screen reader (tested with Apple Voice Over).
Related to, but independent of https://github.com/elifesciences/pattern-library/pull/889.

Improve announcement of search control in site header

---

Jenkinsfile.prod

Allows infrastructure updates to acquire a lock (manually) and stop deployments from happening at the same time.

Introduce lock on journal--prod

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/385/display/redirect which resulted in this pull request.

Updated elife/patterns to 59c6fb9: Updated pattern-library to 1432d14: Style as discreet: links in articles' unordered, non-reference lists

---

app/config/config.yml
app/config/routing.yml

They're not actually being logged (they're filtered out).

Remove CSP report-uri

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/391/display/redirect which resulted in this pull request.

Updated elife/patterns to d566aeb: Updated pattern-library to 2b7a651: Force open article sections if the request is from Google

---

composer.lock

Fixes https://symfony.com/blog/cve-2018-14773-remove-support-for-legacy-and-risky-http-headers

Update Symfony to 3.4.14

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/395/display/redirect which resulted in this pull request.

Updated elife/patterns to 85bc669: Updated pattern-library to e41b0c6: Display annotation highlights always

---

app/Resources/views/page.html.twig

Avoids `foo&amp;bar=baz` if adding extra parameters.

Don't escape GTM IDs

---

app/Resources/views/article.html.twig

Avoid GTM double counting click events within the abstract section of an article.
The way that link clicks are directed to the [`Popup` JavaScript class](https://github.com/elifesciences/pattern-library/blob/develop/assets/js/components/Popup.js) is a blunt instrument (see https://github.com/elifesciences/pattern-library/blob/develop/assets/js/components/DelegateBehaviour.js and https://github.com/elifesciences/journal/blob/develop/app/Resources/views/article.html.twig#L335). In order to determine if a clicked link should be displayed in a popup (for references and authors) it is currently configured to process any click on an anchor element within the article that appears beneath the contextual data pattern (which is most of the article).
This is causing GTM click listeners to fire twice …

Don't delegate abstract's links to popup js

---

src/Helper/ModelName.php
test/Helper/ModelNameTest.php

Fixes 500 error mentioned in https://github.com/elifesciences/issues/issues/4290#issuecomment-422442139.
(GTM was turned on in `demo` recently.)
Might be better to transform the value and override when necessary.

Add digests to model names list

---

app/config/config_ci.yml

Currently logs when running tests are sent to `stderr`, which makes for a very verbose output. This turns them off (might be better to send them somewhere in the longer term though).

Remove logs in tests

---

.docker/php.ini

Current PHPUnit nor Behat can be run on the `app` container as they run out of memory (it's an FPM container so has the low default limit).
This makes it unlimited, which will make it harder to spot leaks when developing.
PHPUnit could be configured with `<ini name="memory_limit" value="-1"/>`, Behat has no equivalent so we'd need a bootstrap file.

Remove memory limit on dev

---

app/config/security.yml
app/config/services.yml
app/config/services_ci.yml
src/Controller/Controller.php
src/Controller/StatusController.php
src/Controller/WhoWeWorkWithController.php
test/Controller/CommunityControllerTest.php
test/Controller/DownloadControllerTest.php
test/Controller/LabsControllerTest.php
test/Controller/MagazineControllerTest.php
test/Helper/DownloadLinkUriGeneratorTest.php

Symfony emits deprecation notices, this prevents most of them (think there's only 2 left, which aren't easy to fix).

Prevent most Symfony deprecation notices

---

src/Controller/SubmitController.php
test/Controller/AuthenticationTest.php
test/Controller/SubmitControllerTest.php
test/WebTestCase.php

When xPub is enabled and clicking the 'Submit my research' header and not logged in, the `/submit` route causes you to log in. However, the `Refer` header is the original page you were on, rather than `/submit`, so you're sent back to that page rather than xPub. It works fine when logged in.
This changes the behaviour on `/submit` to do an internal sub-request, rather than a redirect, which allows us to change the `Referer` header. It also removes a hop.

Fix redirect after logging in on /submit

---

src/Controller/SubmitController.php
src/Security/XpubTokenGenerator.php
src/ViewModel/Factory/SiteHeaderFactory.php
test/Controller/SubmitControllerTest.php
test/Security/XpubTokenGeneratorTest.php
test/ViewModel/Factory/SiteHeaderFactoryTest.php

Changes the site header 'Submit my research' link to always be the `submit_url` setting, unless you're logged in (when it's `/submit`). The JWT passed to Xpub with then contain a new property (currently called `new-session`) indicating whether the new session was caused by being visiting `/submit` or not.

Add new-session property in the xPub JWT

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/411/display/redirect which resulted in this pull request.

Updated elife/patterns to 4c91971: Updated pattern-library to 536421d: Force width of teaser images in single column

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/412/display/redirect which resulted in this pull request.

Updated elife/patterns to 4c1909a: Updated pattern-library to 3bc49e3: Fix single-column teaser image widths

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/414/display/redirect which resulted in this pull request.

Updated elife/patterns to 59fe27d: Allow Button::link static constructor to take an optional id

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/419/display/redirect which resulted in this pull request.

Updated elife/patterns to 4272450: Content header title length

---

README.md

We observed `docker-compose up --build -V` not deleting the `vendor` volume; looking at the man page it may be right as it says `anonymous volumes`.
I suspect that given ours are named in `volumes:` [they are not considered anonymous](https://docs.docker.com/storage/volumes/#remove-volumes) even without a specified host folder:
```
Named volumes have a specific source form outside the container, for example awesome:/bar.
Anonymous volumes have no specific source so when the container is deleted, instruct the Docker Engine daemon to remove them.
```
So most of ours are named, not anonymous; suggesting to default to `docker-compose down -v` to clean them up.

Use docker-compose down -v

---

.docker/parameters.yml
app/config/config_ci.yml
app/config/parameters.yml.dist
src/Controller/ArticlesController.php
test/Controller/ArticleControllerTest.php

For https://github.com/elifesciences/issues/issues/4525
Since we don't want to expand the API yet for a single experiment, we feature flag zero or more article ids so that they will display a bar with a link to an external page with their `reproducible version`, a display of the article that allows to interact with figures and regenerate them by changing their source code.

Add link to reproducible document from article 30274

---

README.md
features/bootstrap/PeopleContext.php
features/people-leadership.feature
src/Controller/AboutController.php
test/Controller/AboutPeopleControllerTest.php

Improves: https://github.com/elifesciences/issues/issues/4778
As a person can only have one type we need Randy Schekman to be considered an active BRE but be introduced as the Founding Editor-in-Chief in the leadership section. The best approach, without extending the schema to support multiple types, is to tag him as type `reviewing-editor` and to target his profile by his label `Founding Editor-in-Chief` in order to bring him into the leadership section on Journal.

Founding Editor-in-Chief may not be of type leadership

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/439/display/redirect which resulted in this pull request.

Updated elife/patterns to ea2de3c: Updated pattern-library to 2c28073: Security: bumps highchart to 6.2.0 for CVE-2018-20801

---

Jenkinsfile
Jenkinsfile.prod

For https://github.com/elifesciences/issues/issues/3676
The image contains assets in the `/srv/journal/web` folder that should be served directly by nginx rather than from the PHP application.

Push web image

---

src/EventListener/EndEmptySessionSubscriber.php

The empty session check in `EndEmptySessionSubscriber` ignores flash messages, so removes the cookie as soon as it's set so they don't appear.
Not been able to recreate the problem in tests (even with Selenium). Going to keep digging, but this initial commit would _hopefully_ get round it at least.

Fix sign up messages not appearing

---

app/Resources/views/article.html.twig

https://github.com/elifesciences/journal/pull/1187/commits/8103931ed6ae519af111a2ea4bbabf9543d5a3e6 broke the path to the logo. (The initial slash bypasses the asset location, but the path was wrong anyway. I thought there was an exception thrown if it could find it...)
/cc @discodavey

Fix publisher logo URL

---

composer.lock

[Resolves](https://github.com/symfony/symfony/releases/tag/v3.4.35):
```
symfony/symfony (v3.4.26)
[2019-11-19T09:07:21.353Z]  * [CVE-2019-18887][]: Use constant time comparison in UriSigner
[2019-11-19T09:07:21.353Z]  * [CVE-2019-18888][]: Prevent argument injection in a MimeTypeGuesser
[2019-11-19T09:07:21.353Z]  * [CVE-2019-18889][]: Forbid serializing AbstractAdapter and TagAwareAdapter instances
```

Update symfony/symfony to 3.4.35

---

app/Resources/views/promotional-collection.html.twig
src/Controller/PromotionalCollectionsController.php

This empty wrapper preserves the layout of the collection page which which the promotional collection is based upon. This is the quickest way to fix the issue and we can follow it up with a real fix later.
See: https://github.com/elifesciences/journal/blob/develop/app/Resources/views/collection.html.twig#L11-L19

Introduce temporary wrapper for spacing

---

Jenkinsfile

These environments will be used to test new journal-cms features that require deploying a branch like https://github.com/elifesciences/issues/issues/5374 and similar tickets.

Temporarily remove continuumtest and continuumtestpreview from automated deployment

---

src/Helper/DownloadLinkUriGenerator.php
test/Helper/DownloadLinkUriGeneratorTest.php

Three of the base64 characters are not url safe:
valid: `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=`
unsafe: `+/=`
A workaround is to substitute these unsafe characters for characters outside of valid `base64` characters and safely swap them back in before decoding.

Avoiding unsafe characters in download uri

---

test/Controller/ArticleControllerTest.php

Tests are failing since schema.org is broken. We should not be making real http requests as part of tests. We should refactor this test to test only our code. For now, we should mark the test as incomplete so that we can continue to make progress on the journal until this is prioritised.

Make test as incomplete

---

.docker/parameters.yml
app/config/parameters.yml.dist
src/Controller/SubmitController.php
test/Assertions.php
test/Controller/SubmitControllerTest.php

New PR as [original branch](https://github.com/elifesciences/journal/pull/1269) name leads to pipeline [failure](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fjournal/detail/PR-1269/9/pipeline).
closes libero/reviewer#837
-  uses return_url query arg to redirect to trusted url
-  uses token_in_query_arg query arg to return the token in token query arg instead of fragment
updates tests

Dynamic submit return from referrer

---

src/ViewModel/Converter/ArticleDownloadLinksListConverter.php
test/Controller/ArticleControllerTest.php

This will alter the download filename of the `Executable version`.

Rename era download file to elife-[article-id]-v[version-no]-era

---

app/Resources/views/page.html.twig

The icon is ignored and the logo is drawn from the elifesciences.org authority hosted with hypothesis

Remove hypothesis services icon

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/485/display/redirect which resulted in this pull request.

Updated elife/patterns to 098c98d: Updated pattern-library to d638d1a: fix: side-by-side menu option no longer appearing on articles

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/488/display/redirect which resulted in this pull request.

Updated elife/patterns to 0ce61cb: Updated pattern-library to 0c692ad: Remove capitalize on article meta

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/490/display/redirect which resulted in this pull request.

Updated elife/patterns to 12ccedf: Updated pattern-library to 88134b8: Remove check for hypothesis services icon

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/502/display/redirect which resulted in this pull request.

Updated elife/patterns to bfaf863: Updated pattern-library to 6d2a15d: remove speech bubble when failure triggered

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/510/display/redirect which resulted in this pull request.

Updated elife/patterns to a57f457: Updated pattern-library to 59b5774: Add word-break for long urls

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/512/display/redirect which resulted in this pull request.

Updated elife/patterns to 65849f2: Updated pattern-library to 50ea381: Revert "Add word-break for long urls" (#777)

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/513/display/redirect which resulted in this pull request.

Updated elife/patterns to 3368cc9: Updated pattern-library to d6016e1: Alternative version of breaking long urls

---

src/ViewModel/Converter/Block/CreatesAssetViewerInline.php
test/Controller/DoiControllerTest.php

If a figure has no supplements the source data is not being shown.
Initially, I thought this could be resolved by exposing a `see all` link for all figures with source data but there is no reason why the source data for the first figure in the asset viewer shouldn't be displayed without the need for an additional http request.

Always display additional assets

---

test/Controller/ArticleControllerTest.php

This was fixed with https://github.com/elifesciences/journal/pull/1424/commits/33b60a779c4890a1af2b2abb4d11affc681f9f1e
This test protects against regression. Prior to the fix the `figuresUri` which possibly contains a fragment id was just used without any attempt to remove the fragment id. This test would have protected us from introducing that bug:
```
There was 1 failure:
1) test\eLife\Journal\Controller\ArticleControllerTest::it_displays_content
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/articles/00001/figures#image1'
+'/articles/00001/figures#figures-and-data#image1'
/srv/journal/test/Controller/ArticleControllerTest.php:2169
```

Add test for see all link on figures with supplements

---

app/config/config.yml
app/config/services.yml
src/Controller/SearchController.php

This is a possible solution for https://github.com/elifesciences/issues/issues/6544
Since we have adjusted the boosting in search we have found that some queries are taking too long to execute and trigger timeout errors. We should increase the timeout on the PHP search application and then really on journal as a client of the search API to determine the timeout threshold. This would also allow us to see how long some of the more intensive queries are taking.

Allow slow connection to search but only implement on the search page

---

src/Controller/Controller.php
test/Controller/PageTestCase.php

This will need more attention if more than one call to action is displayed.
Journal is supposed to be able to handle multiple calls to action but the behaviour is strange when you have more than one. Particularly more than one that is dismissible.
This should be solved first in pattern-library but this should work fine for a single call to action.

Allow call to action to be dismissible

---

Dockerfile.assets_builder
Dockerfile.critical_css
Dockerfile.npm

Issue is that the currently hosted location for the pre-built binary is on a rate limited server, hence when the rate is hit you get 403 errors returned. We shouldn't be relying on npm dependencies to install prebuilt libraries, and should be using those available on the host OS.
This will only fix the issue on CI, trying to run `npm install` locally will still hit the same problem. Updating `gulp-responsive` to use `sharp >= 0.19.0` is required, which works. But `phantomjs-prebuilt` also has the same problem and updating that to version 0.19.0 or greater doesn't work, and `phantomjs` is now deprecated and has been for years.
This patches the problem, but the whole build system here in the Journal project needs a top to bottom review and cleanup
This fixes elifesciences/issues#6665

fix: npm fails to fetch pre-built binary for libvips with http 403

---

src/Controller/AlertsController.php

Update additional newsletter links on the alert pages to point at the content-alert pages.

fix: update links in alert pages

---

Jenkinsfile.prod

Jenkinsfile.prod, ensures all production nodes are registered with the load balancer before attempting to deploy.
addresses the problem we're seeing in issue #7092 where a previous failed deployment can't be solved by re-running the Jenkins job because the LB targets won't ever be healthy.

deploy to prod fix

---

README.md
docker-compose.override.yml

This fixes an issue introduce in: https://github.com/elifesciences/journal/pull/1632
Without this a run of `phpunit` would not have worked locally following the README.

Adjust README to allow for successfully run of unit tests locally

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/612/display/redirect which resulted in this pull request.

Updated elife/patterns to 0dc2368: Updated pattern-library to b49ef93: Possible fix for extra long urls

---

src/Controller/HomeController.php

In anticipation of an increase to 4 covers we need to ensure that only a maximum of 3 covers are brought into the carousel.

Limit cover to 3 for carousel

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/622/display/redirect which resulted in this pull request.

Updated elife/patterns to 3c76a40: Make summary optional because collection, article, and blog article can be null

---

composer.lock

I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/707/display/redirect which resulted in this pull request.

Updated elife/patterns to cbd1039: Updated pattern-library to 4d541e4: Bug: added link. to tag as was missing for image link

---

src/ViewModel/Converter/EventContentHeaderConverter.php
test/Controller/EventControllerTest.php

Removed the use of 'CreatesDate' in 'EventContentHeaderConverter'. The 'meta' variable is now directly assigned with the object's start date via 'ViewModel\Date::simple' instead of using a conditional statement.

feat: update EventContentHeaderConverter to simplify date creation

---

app/config/services.yml

The factory for 'reviewed-preprints' in services.yml has been updated to '@elife.api_sdk.slow'. This change enhances the performance of the reviewed-preprints feature. An unnecessary whitespace has also been removed.

feat: update factory for reviewed-preprints in services.yml

---

.env
Dockerfile.assets_builder
Dockerfile.composer
Dockerfile.npm
Dockerfile.web
docker-compose.override.yml
docker-compose.yml
gulpfile.js

This branch fixes issues with running native ARM images to build journal containers, and reverts most of the workarounds from https://github.com/elifesciences/journal/commit/d6c0984506915fbd0e9e4ce76f34419b7779b75d
The benefits of this are:
- banner images are there
- it will be quite a lot faster.
Todo:
Related https://github.com/elifesciences/issues/issues/8976

Better AppleSilicon support for building support images

---

Dockerfile.composer
README.md

https://blog.packagist.com/deprecating-composer-1-support/ (from 2021) explains that 
> The update rate for new versions will be reduced from every-minute currently to once every 15 minutes. This means new releases will take a few minutes longer to be available for installation with Composer 1.x.
It's possible this is what causes [failures while waiting for a new version of `elife/patterns` to be available](https://alfred.elifesciences.org/job/dependencies/job/dependencies-journal-update-patterns-php/).
Furthermore, https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/ states
> February 1st, 2025: Composer 1.x metadata will become read-only. No new packages or new versions will be visible for Composer 1.x users after this date.
According to …

Upgrade to composer 2 lts

---

.docker/parameters.yml
docker-compose.ci.yml
docker-compose.yml

Following https://symfony.com/doc/current/configuration.html syntax to explicitly interpolate into configuration files rather than relying on the magic behavior that parses environment variables starting with SYMFONY__*
This was shown in the PHPUnit report, when running any single test via `make test`:
```
1x: The support of special environment variables that start with SYMFONY__ (such as "SYMFONY__API_URL_SEARCH_PAGE") is deprecated as of 3.3 and will be removed in 4.0. Use the %env()% syntax instead to get the value of environment variables in configuration files.
1x in BrowseControllerTest::it_shows_reviewed_preprints_on_results from test\eLife\Journal\Controller
```
Tested `make prod` and `make dev` locally, and a full `make test`.

Remove deprecated SYMFONY__* magic environment variables
